spring:
  profiles:
    active: dev
eureka:
  instance:
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
    prefer-ip-address: true
    hostname: ${spring.cloud.client.ipAddress}
---
spring:
  profiles: dev
  data:
    mongodb:
      uri: mongodb://test.1byongche.cn:27017/simulator-car
server:
  port: 9810
tbox:
  hikvision:
    host: 47.100.76.78
    port: 8610
    idle: 30
  threadcn:
    host: 47.100.76.78
    port: 8620
    idle: 30
service:
  car:
    uri: http://47.100.76.78:8420

---

logging:
  config: classpath:logback-spring-${spring.profiles}.xml
spring:
  profiles: test
  data:
    mongodb:
      uri: mongodb://test.1byongche.cn:27017/simulator-car
server:
  port: 8810
tbox:
  hikvision:
    host: 47.100.76.78
    port: 8610
    idle: 30
  threadcn:
    host: 47.100.76.78
    port: 8620
    idle: 30
service:
  car:
    uri: http://47.100.76.78:8420
